#iOS configuration circle ci file
#
version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      #install cocoapods
      - run:
        name: Install CocoaPods
        command: pod install
      #update cocoapods
      - run:
        name: Update CocoaPods
        command: pod update
      #build the app and run test
      - run:
        name: Build and run tests
        command: fastlane scan
        environment:
          SCAN_DEVICE: iPhone 8
          SCAN_SCHEME: SpotifyApp
      
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

